### ISSUE TITLE
Review of scale-out blog post

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/blog#15]
https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L14
We never published anything about funding from Filecoin, nor is it clear that we are legally allowed to (see clause 7 of our [contract with them](https://www.notion.so/ipfs-search/Filecoin-Grant-Agreement-5569c8d0716843f29401920e0391b7e5). I already [asked Aad to go after this](https://matrix.to/#/!kSlurUgSRabrjGZqFn:chat.weho.st/$EcFzywhyqwlnPymIpWgwTkmBTNi4wtMkN6JuFGD8BBU?via=matrix.org). 

In order to provide more clarity; we got funding:

1. From [NLNet](https://nlnet.nl/project/IPFS-search/) through [NGI0](https://www.ngi.eu/funded_solution/ipfs-search/) for the architecture/research to scale from 1 to 5 nodes (~ € 12k) and from 5 to 15 nodes (~ € 12k, again). We executed this around October last year (but were to busy to publish about it, or even claim the money). Feel free to check out our [agreement with them](https://www.notion.so/ipfs-search/NLnet-MoU-2021-6ff94c5e41ee4e6a80d471b6baf8667c).
2. From Filecoin, for the implementation (of the architecture) from 5 to 15 nodes (~ € 9k, haven't claimed it yet, 95% done), from 15 to 50 nodes (about 40% done, ~ € 24k)  and from 50 to   100 nodes (~ € 48k). Our [agreement with them](https://www.notion.so/ipfs-search/Filecoin-Grant-Agreement-5569c8d0716843f29401920e0391b7e5).

Please take a careful look at said agreements to see what exactly we're doing.

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L17
There is no amount of servers with which we can grow exponentially, if our growth in terms of hits per second *or* indexing rate (documents per second added to our index) grow exponentially, this automatically implies that the amount of *storage* capacity and thus servers keeps growing exponentially. The current experiment is for us to *learn how* to scale our infrastructure (up and until 100 nodes, beyond 100 nodes we will likely have to completely rethink everything).

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L23
Capacity is not clearly defined here. In this case it's the *size of our index*. We might also want to mention the *amount of documents* in our index (and how it scaled over time). The other indicator is the amount of user traffic we can handle (hits/second) and the amount of document we're indexing per second.

Note that, so far, I've focused almost exclusively on the indexing rate, because, frankly, we don't have users (don't tell anyone!).

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L30
I was talking about reducing our [marginal cost](https://en.wikipedia.org/wiki/Marginal_cost), to make it cheaper for us to index more things and serve more users.

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L32
I don't know what live servers are, in this context. A dead server is a server which is unreachable over the internet. A live server is a server that's actually working. I think you might mean to say [bare metal](https://en.wikipedia.org/wiki/Bare-metal_server) here. I would definitely encourage you to actually link to resources for any concepts foreign to you, that would definitely make the article more accessible.

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L35
run -> ran

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L36
We're indexing files and directories, not pages (though some of the files are websites).

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L37
Maybe refer to our previous blogpost about the refactor of the crawler (AFAIK, we made such a post, don't 100% remember).

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L41
Actually, *automated* deployment is a *solution* to dealing with multiple servers. Instead of executing a million commands for every server manually, and checking the results, Ansible does this for us. But the architecture, what server does what, and telling that in the correct way to Ansible, was the challenge.

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L46
have -> had
I think you might also want to mention the term [redundancy](https://en.wikipedia.org/wiki/Redundancy_(engineering)) here 

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L47
In the context of the previous sentence, this suggests that out of 3 servers 2 will perform badly, which of course is none sense. Let's refer back to my example; if a company has 3 cars, most of them will be running most of the time and only occasionally one of them is in the garage (unless in PT, where most of them will be in the garage most of the time). Now, if the company has 30 cars, it is very common that there are always 2 or 3 in the garage (just different ones, of course). Now, to stretch this analogy, if those cars are doing package delivery of very important deliveries that are so big they cannot be carried by a single car, to avoid the risk of the delivery not arriving completely, we would send the delivery 2 or even 3 times, spread over multiple cars, so that it is extremely unlikely that the 2 or 3 cars which are unavailable prevent the package delivery. Of course, where the metaphor breaks is that it is *easy* to copy data whereas in the physical world it's expensive to copy delivered articles.

https://github.com/ipfs-search/blog/blob/main/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L48
Just to give some clarification; the master nodes take care of  deciding which shards (parts) of our data go to which servers, and making sure the servers know about each other. More background: https://opster.com/guides/elasticsearch/data-structuring/elasticsearch-dedicated-master-node/

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L51
This is really clear!

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L52
I would suggest explicitly telling that initially we were indexing 1 document at a time and that this proved to be problematic because the amount of coordination (what data lives where, etc.) increased as we scaled up our cluster. So explaining the transition.

https://github.com/ipfs-search/blog/blob/58f87fd413ce5e5b8cea2dfee6664b7da12ed1a8/_drafts/16-04-2022-Scaling-up-the-search.md?plain=1#L53
There's 2 types of redundancy, one of the service (are we always online) and one of the data (making sure we don't loose it, including backups etc.).

Lastly, there's my previous feedback (from the email) regarding the images:
"please note that the graphs are on different timescales, and that the ‘ES nodes’ starts with 3 nodes going to 30 whereas the schema’s for architecture are those for 1 and 3 nodes. I haven’t read the article so it might be intentional, just to make you aware."

**Comment by Szeket** [comment]
hej, thanks a lot, I am moving my article to notion now.
